name: Maven Release

# https://stackoverflow.com/questions/58254332/maven-release-from-github-actions
on:
  workflow_dispatch:
    branches: [ "master" ]
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
      - name: Log the Input
        run: |
          echo "### Creating new Tag: $Tag"
          echo "### Creating new Snapshot: $Snapshot"
        env:
          Tag: ${{ inputs.releaseVersion }}
          Snapshot: ${{ inputs.developmentVersion }}
          
      - uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven Release
        continue-on-error: true # TODO: currently release is failing when uploading released pom
        run: |
          mvn -version
          echo "### Release started. Released Version ${{ github.event.inputs.releaseVersion }}. New Snapshot is: ${{ github.event.inputs.developmentVersion }}"
          mvn -B -e release:prepare release:perform -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Get Deployable
        run: |
          echo "### Retrieving deployable jar ###"
          curl 'https://maven.pkg.github.com/boeckli-swp/wsl-java11/org/example/wsl-java11/${{ github.event.inputs.releaseVersion }}/wsl-java11-${{ github.event.inputs.releaseVersion }}.jar' \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -L \
            -o target/deployable.jar
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}  
